!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!                                                         ! 
!    FILE: inirea.F90                                     !
!    CONTAINS: subroutine ReadFlowField                   !
!                                                         ! 
!    PURPOSE: Initialization routine. Reads in a flow     !
!     snapshot generated by a previous simulation, and    !
!     interpolates to the current grid if necessary       !
!                                                         !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

subroutine ReadFlowField

    use mpih
    use decomp_2d
    use local_arrays
    use param

    implicit none

    character*70                        :: filename,dsetname
    integer                             :: nxo,nyo,nzo
    integer                             :: istro3
    real                                :: stro3
    logical                             :: fexist
      
    !EP   Reading old grid information by master
    filename = trim('continua_master.h5')

    inquire(file=filename,exist=fexist)
    if (.not.fexist) then 
        write(*,*) 'Continuation files not found'
        call MpiAbort
    end if

    if (ismaster) then
        dsetname = trim('nx')
        call HdfSerialReadIntScalar(dsetname,filename,nxo)
        dsetname = trim('ny')
        call HdfSerialReadIntScalar(dsetname,filename,nyo)
        dsetname = trim('nz')
        call HdfSerialReadIntScalar(dsetname,filename,nzo)
        dsetname = trim('time')
        call HdfSerialReadRealScalar(dsetname,filename,time)
        dsetname = trim('istr3')
        call HdfSerialReadIntScalar(dsetname,filename,istro3)
        dsetname = trim('str3')
        call HdfSerialReadRealScalar(dsetname,filename,stro3)
    endif
      
    call MpiBarrier
    call MpiBcastInt(nxo)
    call MpiBcastInt(nyo)
    call MpiBcastInt(nzo)
    call MpiBcastInt(istro3)
    call MpiBcastReal(stro3)
    call MpiBcastReal(time)
    
    !EP   Check whether grid specifications have been updated
    if(nyo.ne.ny.or.nxo.ne.nx.or.nzo.ne.nz.or.istro3.ne.istr3.or.(abs(stro3-str3).gt.1e-8)) then
        if(ismaster) write(*,*) "!! Interpolation not supported at this time !!"
        call MpiAbort
    else
        filename = trim('continua_vx.h5')
        call HdfReadRealHalo3D(filename,vx,xstart(2),xend(2),xstart(3),xend(3),nx,ny,nz)
        filename = trim('continua_vy.h5')
        call HdfReadRealHalo3D(filename,vy,xstart(2),xend(2),xstart(3),xend(3),nx,ny,nz)
        filename = trim('continua_vz.h5')
        call HdfReadRealHalo3D(filename,vz,xstart(2),xend(2),xstart(3),xend(3),nx,ny,nz)
        filename = trim('continua_temp.h5')
        call HdfReadRealHalo3D(filename,temp,xstart(2),xend(2),xstart(3),xend(3),nx,ny,nz)
        filename = trim('continua_co2.h5')
        call HdfReadRealHalo3D(filename,co2,xstart(2),xend(2),xstart(3),xend(3),nx,ny,nz)
        filename = trim('continua_h2o.h5')
        call HdfReadRealHalo3D(filename,h2o,xstart(2),xend(2),xstart(3),xend(3),nx,ny,nz)
    endif

    return

    end